---
namespace: fmjstudios
name: nebula
version: 0.0.1
readme: README.md
authors:
  - Maximilian Gindorfer <info@fmj.dev>
description: Ansible Collection for Nebula VPN Mesh management
license_file: 'LICENSE'
tags:
  - vpn
  - mesh
  - zero-trust
  - site-to-site
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: https://fmj.dev
issues: http://example.com/issue/tracker
build_ignore:
  - .gitignore
  - LICENSE
  - Makefile
  - AUTHORS
  - .vscode
  - .github
