# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Configure Libvirt as the virtual machine provider
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.host = "localhost"
    libvirt.uri = "qemu:///system"
    libvirt.qemu_use_session = false
    libvirt.forward_ssh_port = true
  end

  # Configure Ansible controller
  config.vm.define "ctrl" do |vm1|
    vm1.vm.box = "generic/ubuntu2204"
    vm1.vm.hostname = "ctrl.local"
    vm1.vm.disk :disk,
      size: "25GB",
      primary: true
    
    # Libvirt machine specific settings
    vm1.vm.provider :libvirt do |lb|
      lb.memory = 2048
      lb.cpus = 2
    end
      
    # Private networking
    vm1.vm.network :private_network,
      :ip => "172.16.0.100",
      :libvirt__dhcp_enabled => false,
      :libvirt__domain_name => "ctrl.local"
  end

  # Configure Ansible managed node 1
  config.vm.define "node1" do |vm1|
    vm1.vm.box = "generic/ubuntu2204"
    vm1.vm.hostname = "node1.local"
    vm1.vm.disk :disk,
      size: "25GB",
      primary: true
    
    # Libvirt machine specific settings
    vm1.vm.provider :libvirt do |lb|
      lb.memory = 2048
      lb.cpus = 2
    end
      
    # Private networking
    vm1.vm.network :private_network,
      :ip => "172.16.0.101",
      :libvirt__dhcp_enabled => false,
      :libvirt__domain_name => "node1.local"
  end

end

