---
_go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'

_go_arch: '{{ _go_arch_map[ansible_architecture] | default(ansible_architecture) }}'


_nebula_repo: 'slackhq/nebula'
_nebula_dist_url: 'https://github.com/{{ _nebula_repo }}/releases/download/v{{ nebula_version }}'

_nebula_checksum_url: '{{ _nebula_dist_url }}/SHASUM256.txt'
_nebula_release_url: '{{ _nebula_dist_url }}/nebula-{{ _go_arch }}.tar.gz'

https://github.com/slackhq/nebula/releases/download/v1.7.2/nebula-linux-amd64.tar.gz